services:
  - type: web
    name: orba
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: orba-db
          property: connectionString
      - key: PORT
        value: 3001
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: MASTER_SEED
        sync: false
      - key: OPERATOR_PRIVATE_KEY
        sync: false
      - key: COINGECKO_API_KEY
        sync: false
      - key: API_FOOTBALL_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: CELO_RPC_URL
        value: https://forno.celo-sepolia.celo-testnet.org
      - key: PREDICTION_MARKET_ADDRESS
        value: "0x62fB5F476B4916e81B323b2381E7903a86049429"

databases:
  - name: orba-db
    plan: free
    databaseName: orba
    user: orba
